### ISSUE TITLE
Release 0.7.0

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-api-client#54]
We should do a minor release after the following issues have merged:

- [x] #50 list all enrollments, with available filters for user or course
- [x] #51 Query grades by course
- [x] #53 Create student enrollments for all modes

followed by an update to the requirements in the mitxpro app

**Comment by pdpinch** [comment]
Closed via #56
